window.posts = [
  {
    slug: "post25.html",
    title: "Oxygen Therapy in Canine Heart Disease:",
    subtitle: "The Science of the Diffusion Barrier and the Transition to Home Care",
    date: "April 22, 2026",
    reviewed: "April 22, 2026",
    author: "Dave Evans",
    authorRole: "MA VetMB PgC(SADI) PgC(SAC) MRCVS",
    authorLink: "../about.html#daveevans",
    series: "Dog Heart Foundations", // The name of the course
    seriesOrder: 7,                 // Step 6
    category: "Medication",
    readTime: "9 min read",
    group: "management",
    audience: "both",
    featured: false,
    image: "/images/frenchieoxygen",
    snippet: "In <strong>congestive heart failure (CHF)</strong>, few interventions feel as immediately life-saving as oxygen. When a dog is struggling to breathe, giving oxygen is instinctive, and often correct. But here’s the problem: <em>Once that crisis has passed, more oxygen is not always better, and may not help at all.</em>"
  },  
  {
    slug: "post24.html",
    title: "Diuretic Therapy in Heart Failure",
    subtitle: "Why we use furosemide (lasix) and when...",
    date: "April 20, 2026",
    reviewed: "April 20, 2026",
    author: "Dave Evans",
    authorRole: "MA VetMB PgC(SADI) PgC(SAC) MRCVS",
    authorLink: "../about.html#daveevans",
    series: "Dog Heart Foundations", // The name of the course
    seriesOrder: 6,                 // Step 6
    category: "Medication",
    readTime: "9 min read",
    group: "management",
    audience: "both",
    featured: false,
    image: "/images/medications.jpeg",
    snippet: "<strong>Diuretic therapy</strong> is the primary tool used by vets to manage congestive heart failure, yet its application requires a sophisticated understanding of renal physiology, cardiac remodelling, and the precise timing of intervention."
  },  
  {
    slug: "post23.html",
    title: "Echocardiography Basics 4: Why the Long-Axis Left Atrium (LAD) is Often Better",
    subtitle: "Lots of reasons to learn this over LA:Ao...",
    date: "April 19, 2026",
    reviewed: "April 19, 2026",
    author: "Dave Evans",
    authorRole: "MA VetMB PgC(SADI) PgC(SAC) MRCVS",
    authorLink: "../about.html#daveevans",
    category: "Echocardiography",
    level: "Beginner", 
    series: "Foundations of Echo",
    seriesOrder: 4,
    technique: "Right-Sided SAX",
    readTime: "9 min read",
    group: "diagnosis",
    audience: "vet",
    featured: false,
    image: "/images/LADmeasure.jpg",
    snippet: "The LAD measurement has lots of benefits and improvements compared to using the LA:Ao. Lets have a look at how its done, and how we can account for different sized dogs."
  },    
  {
    slug: "post22.html",
    title: "Echocardiography Basics 3: Complications with the Left Atrium to Aorta Ratio (LA:Ao)",
    subtitle: "The flaws and controversies that can trip you up...",
    date: "April 16, 2026",
    reviewed: "April 16, 2026",
    author: "Dave Evans",
    authorRole: "MA VetMB PgC(SADI) PgC(SAC) MRCVS",
    authorLink: "../about.html#daveevans",
    category: "Echocardiography",
    level: "Beginner", 
    series: "Foundations of Echo",
    seriesOrder: 3,
    technique: "Right-Sided SAX",
    readTime: "12 min read",
    group: "diagnosis",
    audience: "vet",
    featured: false,
    image: "/images/LAAo-pulmvein-an.jpg",
    snippet: "While the LA:Ao is the first step on most echo journeys, it has a lot of flaws and controversies. What are they, and how can we mitigate them?"
  },  
  {
    slug: "post21.html",
    title: "Echocardiography Basics 2: The Left Atrium to Aorta Ratio (LA:Ao)",
    subtitle: "Getting started with Echo: Measuring your first important ratio",
    date: "April 14, 2026",
    reviewed: "April 14, 2026",
    author: "Dave Evans",
    authorRole: "MA VetMB PgC(SADI) PgC(SAC) MRCVS",
    authorLink: "../about.html#daveevans",
    category: "Echocardiography",
    level: "Beginner", 
    series: "Foundations of Echo",
    seriesOrder: 2,
    technique: "Right-Sided SAX",
    readTime: "8 min read",
    group: "diagnosis",
    audience: "vet",
    featured: false,
    image: "/images/LAAo-whale.jpg",
    snippet: "Left atrial size is a window into cardiac health, in both dogs and cats. Heart failure results from too much pressure in the left atrium, and size is directly linked to this pressure. But how do we measure it?"
  },  
  {
    slug: "post20.html",
    title: "Echocardiography Basics 1: The Views",
    subtitle: "Getting started with Echo: Getting the right views",
    date: "April 13, 2026",
    reviewed: "April 13, 2026",
    author: "Dave Evans",
    authorRole: "MA VetMB PgC(SADI) PgC(SAC) MRCVS",
    authorLink: "../about.html#daveevans",
    category: "Echocardiography",
    level: "Beginner", 
    series: "Foundations of Echo",
    seriesOrder: 1,
    technique: "Right-Sided views",
    readTime: "15 min read",
    group: "diagnosis",
    audience: "vet",
    featured: false,
    image: "/images/heart-dog-sax.jpg",
    snippet: "Understanding the dog’s heart positioning is crucial. Echo is full of confusing terms, but let’s break them down."
  },
  {
    slug: "post19.html",
    title: "Navigating the DMVD Journey: A Clinical Guide to Diet and Supplements",
    subtitle: "How can we look to diet and supplements to help...",
    date: "April 3, 2026",
    reviewed: "April 3, 2026",
    author: "Dave Evans",
    authorRole: "MA VetMB PgC(SADI) PgC(SAC) MRCVS",
    authorLink: "../about.html#daveevans",
    category: "Murmurs",
    readTime: "12 min read",
    group: "management",
    audience: "both",
    featured: true,
    image: "/images/foodandsupplements.jpg",
    snippet: "If you have recently returned from the vet and heard the words “heart murmur” - or they have specifically diagnosed “Degenerative Mitral Valve Disease (DMVD)”, you are likely feeling a mix of anxiety - and a strong desire to act. Let’s have a look at how diet and supplements can help."
  },
  {
    slug: "post18.html",
    title: "The 60-Day Warning: How Pet Wearables are Rewriting the Rules of Cardiac Care",
    subtitle: "Moving beyond just relying on the sleeping respiratory rate...",
    date: "February 28, 2026",
    reviewed: "February 28, 2026",
    author: "Dave Evans",
    authorRole: "MA VetMB PgC(SADI) PgC(SAC) MRCVS",
    authorLink: "../about.html#daveevans",
    category: "Monitoring",
    readTime: "6 min read",
    group: "management",
    audience: "both",
    featured: true,
    image: "/images/dogjump.jpeg",
    snippet: "For years, the management of dogs with degenerative mitral valve disease (DMVD) has relied on a single, vital metric: the Sleeping Respiratory Rate (SRR). But as any cardiologist will tell you, a spike in respiratory rate is a late-stage indicator. By the time the breathing changes, the crisis of congestive heart failure (CHF) has often already started."
  },
  {
    slug: "post17.html",
    title: "The State of Pet Wearables in 2026: From Activity Tracking to Medical-Grade Surveillance",
    subtitle: "What's going on in Pet Wearables right now?",
    date: "February 27, 2026",
    reviewed: "February 27, 2026",
    author: "Dave Evans",
    authorRole: "MA VetMB PgC(SADI) PgC(SAC) MRCVS",
    authorLink: "../about.html#daveevans",
    category: "Monitoring",
    readTime: "6 min read",
    group: "management",
    audience: "both",
    featured: true,
    image: "/images/wearingcollar.jpg",
    snippet: "As we move into early 2026, the landscape of pet wearable technology has reached a definitive tipping point. The era of the “pet Fitbit” - simple accelerometers that merely count steps - is officially over."
  },
  {
    slug: "post16.html",
    title: "Monitoring Your Pet's Breathing at Home: A Vet Cardiologist’s Guide",
    subtitle: "How do you know if you're doing it right?",
    date: "February 24, 2026",
    reviewed: "February 24, 2026",
    author: "Dave Evans",
    authorRole: "MA VetMB PgC(SADI) PgC(SAC) MRCVS",
    authorLink: "../about.html#daveevans",
    series: "Cat Heart Foundations", // The name of the course
    seriesOrder: 4,                 // Step 4
    category: "Monitoring",
    readTime: "6 min read",
    group: "management",
    audience: "both",
    featured: false,
    image: "/images/srrcount.jpg",
    snippet: "Home monitoring of the Sleeping Respiratory Rate (SRR) is one of the most powerful tools we have in managing heart disease. However, it only works if the data is clean. If we measure breathing at the wrong time, we get “noise” instead of clinical insight."
  },
  {
    slug: "post15.html",
    title: "Why Heart Failure Happens Suddenly: The 'Parachute' Problem",
    subtitle: "Why does a healthy dog sometimes go into a respiratory crisis out of the blue? The rupture of the chordae tendineae...",
    date: "January 18, 2026",
    reviewed: "January 18, 2026",
    author: "Dave Evans",
    authorRole: "MA VetMB PgC(SADI) PgC(SAC) MRCVS",
    authorLink: "../about.html#daveevans",
    series: "Dog Heart Foundations", // The name of the course
    seriesOrder: 3,                 // Step 3
    category: "Diagnosis",
    readTime: "6 min read",
    group: "foundations",
    audience: "owner",
    featured: false,
    image: "/images/rupturedchordae.jpg",
    snippet: "Why does a healthy dog sometimes go into a respiratory crisis out of the blue? The physics of the heart changes when a chordae tendineae ruptures."
  },
  {
    slug: "post14.html",
    title: "The Maven Smart Collar: A Veterinary Cardiologist’s In-Depth Review",
    subtitle: "How does it measure up to the traditional approach?",
    date: "January 12, 2026",
    reviewed: "March 3, 2026",
    author: "Dave Evans",
    authorRole: "MA VetMB PgC(SADI) PgC(SAC) MRCVS",
    authorLink: "../about.html#daveevans",
    category: "Monitoring",
    readTime: "10 min read",
    group: "management",
    audience: "owner",
    featured: false,
    image: "/images/mavenbox2.jpg",
    snippet: "A full look into the Maven Smart Collar device and how it can be used for continuous monitoring of Congestive Heart Failure."
  },
  {
    slug: "post13.html",
    title: "Monitoring Heart Failure at Home: Are Smart Collars Worth It?",
    subtitle: "How do they compare to traditional counting methods?",
    date: "January 6, 2026",
    reviewed: "January 6, 2026",
    author: "Dave Evans",
    authorRole: "MA VetMB PgC(SADI) PgC(SAC) MRCVS",
    authorLink: "../about.html#daveevans",
    category: "Monitoring",
    readTime: "8 min read",
    group: "management",
    audience: "owner",
    featured: true,
    image: "/images/tracker_cat.jpg",
    snippet: "How do you really monitor your pet’s heart disease at home? We look at whether tracking collars and smart monitors are worth the investment."
  },
  {
    slug: "post12.html",
    title: "Understanding Heart Murmurs in Cats",
    subtitle: "Why it happens, what it means and what you should do",
    date: "November 9, 2025",
    reviewed: "November 9, 2025",
    author: "Dave Evans",
    authorRole: "MA VetMB PgC(SADI) PgC(SAC) MRCVS",
    authorLink: "../about.html#daveevans",
    series: "Cat Heart Foundations", // The name of the course
    seriesOrder: 1,                 // Step 1
    category: "Murmurs",
    readTime: "7 min read",
    group: "foundations",
    audience: "owner",
    featured: false,
    image: "/images/cat_laptop.jpeg",
    snippet: "Has your vet heard a murmur in your cat's heart? Is it serious? Should you be worried? We break down why feline murmurs are different from dogs."
  },
  {
    slug: "post11.html",
    title: "The Rise of the Corporate Vet Clinic: What It Means for You and Your Pet",
    subtitle: "Are You Being Overcharged For Petcare?",
    date: "October 31, 2025",
    reviewed: "October 31, 2025",
    author: "Dave Evans",
    authorRole: "MA VetMB PgC(SADI) PgC(SAC) MRCVS",
    authorLink: "../about.html#daveevans",
    category: "Industry",
    readTime: "6 min read",
    group: "foundations",
    audience: "both",
    featured: false,
    image: "/images/blog11piechart.jpeg",
    snippet: "Over 60% of UK vet practices are now corporate-owned. What does this shift mean for your pet's care and your wallet?"
  },
  {
    slug: "post10.html",
    title: "Hypertrophic Cardiomyopathy in Cats",
    subtitle: "A Detailed Guide for Cat Owners and Breeders",
    date: "September 22, 2025",
    reviewed: "September 22, 2025",
    author: "Dave Evans",
    authorRole: "MA VetMB PgC(SADI) PgC(SAC) MRCVS",
    authorLink: "../about.html#daveevans",
    series: "Cat Heart Foundations", // The name of the course
    seriesOrder: 2,                 // Step 2
    category: "Diagnosis",
    readTime: "10 min read",
    group: "foundations",
    audience: "both",
    featured: true,
    image: "/images/cat_laptop.jpeg",
    snippet: "Hypertrophic Cardiomyopathy is the most common heart condition in cats, and the most common reason for a murmur. But there is lots of misunderstanding surrounding this condition, and we tackle a few of the myths that exist."
  },
  {
    slug: "post9.html",
    title: "What is congestive heart failure (CHF)?",
    subtitle: "No one wants to hear their pet has 'heart failure'. How bad is it?",
    date: "August 5, 2025",
    reviewed: "August 5, 2025",
    author: "Dave Evans",
    authorRole: "MA VetMB PgC(SADI) PgC(SAC) MRCVS",
    authorLink: "../about.html#daveevans",
    category: "Diagnosis",
    readTime: "8 min read",
    group: "foundations",
    audience: "owner",
    featured: false,
    image: "/images/dogjump.jpeg",
    snippet: "Heart failure is a scary term, but it doesn't always mean the end of the road. We explain what CHF actually is and how it's managed."
  },
  {
    slug: "post8.html",
    title: "What does pimobendan do to help in degenerative mitral valve disease?",
    subtitle: "Pimobendan (known as Vetmedin / Cardisure) has amazing benefits to treat DMVD. Should all dogs with a heart murmur get pimobendan?",
    date: "July 13, 2025",
    reviewed: "July 13, 2025",
    author: "Dave Evans",
    authorRole: "MA VetMB PgC(SADI) PgC(SAC) MRCVS",
    authorLink: "../about.html#daveevans",
    series: "Dog Heart Foundations", // The name of the course
    seriesOrder: 5,                 // Step 5
    category: "Medication",
    readTime: "6 min read",
    group: "management",
    audience: "both",
    featured: false,
    image: "/images/medications.jpeg",
    snippet: "Pimobendan (Vetmedin or Cardisure) has amazing benefits for heart disease. Should all dogs with a heart murmur get pimobendan? When should I put my dog on it? We discuss the complexities behind this drug and when it should be started."
  },
  {
    slug: "post7.html",
    title: "The different stages of Degenerative Mitral Valve Disease.",
    subtitle: "What are these ACVIM categories I have heard about? Why does my vet go on about them?",
    date: "July 1, 2025",
    reviewed: "July 1, 2025",
    author: "Dave Evans",
    authorRole: "MA VetMB PgC(SADI) PgC(SAC) MRCVS",
    authorLink: "../about.html#daveevans",
    series: "Dog Heart Foundations", // The name of the course
    seriesOrder: 4,                 // Step 4
    category: "Diagnosis",
    readTime: "8 min read",
    group: "foundations",
    audience: "both",
    featured: false,
    image: "/images/acvim_stages.png",
    snippet: "Veterinary cardiologists use stages to describe Degenerative Mitral Valve Disease (DMVD). Understanding where your pet sits helps guide treatment and management."
  },
  {
    slug: "post6.html",
    title: "Degenerative Mitral Valve Disease Explained",
    subtitle: "What does it mean for my pet?",
    date: "June 30, 2025",
    reviewed: "June 30, 2025",
    author: "Dave Evans",
    authorRole: "MA VetMB PgC(SADI) PgC(SAC) MRCVS",
    authorLink: "../about.html#daveevans",
    series: "Dog Heart Foundations", // The name of the course
    seriesOrder: 2,                 // Step 2
    category: "Diagnosis",
    readTime: "6 min read",
    group: "foundations",
    audience: "owner",
    featured: false,
    image: "/images/ckcs2.jpg",
    snippet: "DMVD is the most common heart disease in dogs. We explain the underlying cause and what it means for your pet's future."
  },
  {
    slug: "post5.html",
    title: "Should I give my cat with HCM Rapamycin (Felycin-CA1)?",
    subtitle: "Why all the hype? What should we be doing? Is Felycin the future of this disease?",
    date: "May 29, 2025",
    reviewed: "June 2, 2025",
    author: "Dave Evans",
    authorRole: "MA VetMB PgC(SADI) PgC(SAC) MRCVS",
    authorLink: "../about.html#daveevans",
    category: "Medication",
    readTime: "8 min read",
    group: "management",
    audience: "vet",
    featured: false,
    image: "/images/rapacat.jpeg",
    snippet: "Why all the hype? Is Rapamycin (Felycin) the future of HCM treatment, or is it just another social media trend?"
  },
  {
    slug: "post4.html",
    title: "Coughing in Dogs and Cats",
    subtitle: "Is it a Heart Problem? Should I Be Worried?",
    date: "April 29, 2025",
    reviewed: "April 29, 2025",
    author: "Dave Evans",
    authorRole: "MA VetMB PgC(SADI) PgC(SAC) MRCVS",
    authorLink: "../about.html#daveevans",
    category: "Diagnosis",
    readTime: "12 min read",
    group: "foundations",
    audience: "owner",
    featured: false,
    image: "/images/dog_glasses.jpg",
    snippet: "Does your dog sound like it’s trying to clear its throat? Or maybe your cat is making a strange, retching sound? Coughing in pets can be alarming—but what does it actually mean? We look at the difference between heart-related and lung-related coughs."
  },
  {
    slug: "post3.html",
    title: "What is an Echo?",
    subtitle: "Has Your Vet Recommended an Echo? What Does This Mean for Your Pet?",
    date: "March 11, 2025",
    reviewed: "March 11, 2025",
    author: "Dave Evans",
    authorRole: "MA VetMB PgC(SADI) PgC(SAC) MRCVS",
    authorLink: "../about.html#daveevans",
    series: "Cat Heart Foundations", // The name of the course
    seriesOrder: 3,                 // Step 3
    category: "Diagnosis",
    readTime: "8 min read",
    group: "foundations",
    audience: "owner",
    featured: false,
    image: "/images/kittenecho_sm.jpg",
    snippet: "Has your vet recommended an 'echo'? Learn what this ultrasound involves and why it's the gold standard for cardiac diagnosis."
  },
  {
    slug: "post2.html",
    title: "Sleeping Respiratory Rate (SRR)",
    subtitle: "What is it? Why measure it? When is it important?",
    date: "March 3, 2025",
    reviewed: "April 20, 2026",
    author: "Dave Evans",
    authorRole: "MA VetMB PgC(SADI) PgC(SAC) MRCVS",
    authorLink: "../about.html#daveevans",
    category: "Monitoring",
    readTime: "5 min read",
    group: "management",
    audience: "owner",
    featured: false,
    image: "/images/kittenasleep.jpg",
    snippet: "Monitoring breathing rate during sleep provides early clues to heart problems. Find out how to perform this vital check at home."
  },
  {
    slug: "post1.html",
    title: "🩺 Heart Murmurs in Dogs: What You Need to Know",
    subtitle: "Has your vet told you your dog has a heart murmur? Is it serious? Should you be worried?",
    date: "March 3, 2025",
    reviewed: "March 3, 2025",
    author: "Dave Evans",
    authorRole: "MA VetMB PgC(SADI) PgC(SAC) MRCVS",
    authorLink: "../about.html#daveevans",
    series: "Dog Heart Foundations", // The name of the course
    seriesOrder: 1,                 // Step 1
    category: "Murmurs",
    readTime: "10 min read",
    group: "foundations",
    audience: "owner",
    featured: false,
    image: "/images/ckcs.jpeg",
    snippet: "Heart murmurs are often the first sign of heart disease. Learn how they are diagnosed and what they mean for your pet's health."
  }
];